/**
 * @file    config_macros.h
 * @brief   Configuration macros and common includes for use throughout the project
 * @author  Karol Wojslaw (karol.wojslaw@student.manchester.ac.uk)
 */

#pragma once

#include <string.h>

#include "esp_check.h"
#include "esp_err.h"
#include "esp_log.h"

/* System self-test (ZCO generated by the ESP32) */
// #define SYS_SELF_TEST  // System self-test on/off macro

/* PIN Assignment */
#define ZCO_PIN 4
#define TEST_PIN 12
#define WS2812_PIN 5

/* WS2812 & RMT*/
#define WS2812_RMT_CHANNEL 1    // RMT channel to be used for WS2812
#define WS2812_BITS_PER_CMD 24  // No of bits per command
#define WS2812_T0H 14           // Bit 0, high time
#define WS2812_T1H 28           // Bit 1, low time
#define WS2812_T0L 32           // Bit 0, low time
#define WS2812_T1L 24           // Bit 1, high time

/* WiFi */
#define WIFI_SSID "TP_LINK_7522"
#define WIFI_PASS "TwojaStara7522"

/* Timer */
#define TIMER_DIVIDER (2)  //  Hardware timer clock divider (80/2 = 40 MHz)
#define TIMER_GROUP TIMER_GROUP_0
#define TIMER_NUM TIMER_0

/* SNTP */
#define SNTP_SYNCH_RETRY 10    // Max number of SNTP synchronisation attempts
#define SNTP_SYNCH_DELAY 2000  // Delay in ms between first and successive attempts to synch. time

/* MQTT */
#define MQTT_URI "mqtt://mqtt3.thingspeak.com"               // ThingSpeak MQTT URI
#define MQTT_PORT 1883                                       // TCP Port
#define MQTT_USERNAME "MxEJJyY4MwYHCS0TNzksJx4"              // Device Username
#define MQTT_PASSWORD "KBbyTJRU5/dlf+Fd+40Yu7pJ"             // Device Password
#define MQTT_ID "MxEJJyY4MwYHCS0TNzksJx4"                    // Device ID
#define MQTT_TOPIC "channels/2033438/publish"                // Frequency/time channel topic
#define MQTT_MEAS_PER_BURST 25                               // Number of measurement per one burst MQTT upload
#define MQTT_MESSAGE_SIZE (60 + (MQTT_MEAS_PER_BURST * 15))  // Size of the MQTT message string

/* Frequency measurement */
#define ESP_INTR_FLAG_DEFAULT 0
#define PULSES_PER_MEAS 10  // Number of interrupt pulses for one f measurement (50/... for meas per s)